import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/contexts/AuthContext";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`antialiased`}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        <Toaster
          toastOptions={{
            success: {
              duration: 3000,
              style: { background: "#4CAF50", color: "#fff" },
            },
            error: {
              duration: 5000,
              style: { background: "#F44336", color: "#fff" },
            },
            loading: {
              duration: 3000,
              style: { background: "#FF9800", color: "#fff" },
            },
          }}
        />
      </body>
    </html>
  );
}
